<?php
/**
 * @file
 * Mica Datasets Crosstab module file
 */

//function getTime() {
//  $mtime = microtime();
//  $mtime = explode(" ", $mtime);
//  $mtime = $mtime[1] + $mtime[0];
//  return $mtime;
//}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_studies_export_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  $links = array();

  switch ($root_path) {

    case 'node/%':
      $node = $router_item['map']['1'];
      switch ($node->type) {
        case 'study':
          //todo verify access to this action, button should be visible only if user has 'can export studies' permission.
          if (node_access('create', 'population')) {
            $links['export-population'] = array(
              '#theme' => 'menu_local_action',
              '#weight' => -30,
              '#link' => array(
                'title' => t('Export'),
                'href' => 'node/' . $node->nid . '/export',
              ),
            );
          }
      }
      break;

  }

  $data['actions']['output'] = array_merge($data['actions']['output'], $links);

}

/**
 * Implements hook_menu().
 */
function mica_studies_export_menu() {

  $items = array();

  $items['node/%node/export'] = array(
    'title' => 'Export nodes',
    //todo verify access to this action, button should be visible only if user has 'can export studies' permission.
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'page callback' => 'mica_studies_export_batch_export',
    'page arguments' => array(1),
    'weight' => 5,
    'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}

function mica_studies_export_batch_export($study) {

  if (is_numeric($study)) {
    $study = node_load($study);
  }

  $wrapper = entity_metadata_wrapper('node', $study);

  $operations = array();
  // extract nid to export
  $nids = _mica_studies_export_find_nodes($study->nid);
  foreach ($nids as $nid) {
    $operations[] = array('_mica_studies_export_gen_xml', array($nid));
  }

  // prepare batch steps
  batch_set(array(
    'operations' => $operations,
    'finished' => 'mica_studies_export_bach_finished',
  ));
  $redirect = 'node/' . $nids[0];

  batch_process($redirect);

}

function mica_studies_export_bach_finished($success, $results, $operations) {

}

function _mica_studies_export_gen_xml($nid, &$context) {
  $wrapper = entity_metadata_wrapper('node', $nid);
 // dpm($wrapper->type->value());
  $context['message'] = t('Processing Node "@title"', array('@title' => $wrapper->title->value()));
  $doc = new DOMDocument('1.0', 'utf-8');

  $type = $doc->createElement($wrapper->type->value());
  $doc->appendChild($type);
  $title = $doc->createElement('title',$wrapper->title->value());
    $type->appendChild($title);
  $uuid = $doc->createElement('uuid',$wrapper->uuid->value());
  $type->appendChild($uuid);
  $myxml = $doc->saveXML();

  file_save_data($myxml,'public://export-'.$wrapper->type->value().'-'.$wrapper->nid->value().'.xml', FILE_EXISTS_REPLACE);

//  dpm();
// Nous insérons le nouvel élément en tant que racine (enfant du document)



}



function _mica_studies_export_find_nodes($study_nid) {
  $nids = array();
  $nids[] = $study_nid;

  $study_wrapper = entity_metadata_wrapper('node', $study_nid);
  foreach ($study_wrapper->field_study_populations->getIterator() as $pop_wrapper) {
    $nids[] = $pop_wrapper->nid->value();
    foreach ($pop_wrapper->field_pop_dce->getIterator() as $dce_wrapper) {
      $nids[] = $dce_wrapper->nid->value();
    }
  }
  foreach ($study_wrapper->field_investigators->getIterator() as $investigator_wrapper) {
    $nids[] = $investigator_wrapper->nid->value();
  }
  foreach ($study_wrapper->field_contacts_ref->getIterator() as $contact_wrapper) {
    $nids[] = $contact_wrapper->nid->value();
  }

//  $study_wrapper = entity_metadata_wrapper('node', $study->nid);

  return $nids;
}
