<?php
/**
 * @file
 * Mica Studies Export  file
 */

include_once('mica_studies_export_contact.inc');
include_once('mica_studies_export_study.inc');
include_once('mica_studies_export_population.inc');
include_once('mica_studies_export_dce.inc');

function mica_studies_export_mica_export_find_related_nids($node) {
  if ($node->type !== 'study') {
    return NULL;
  }
  return mica_export_find_related_nids($node);
}

function mica_studies_export_mica_export_permission_parameters() {
  return array(
    'export studies' => array(
      'title' => t('Export XML Studies'),
      'description' => t('Allow users exporting studies')
    )
  );
}

function mica_studies_export_mica_export_can_export_node($node) {
  return (($node->type == 'study') && (node_access('view', $node) && user_access('export studies')));
}

/**
 * Implements hook_menu().
 */

function mica_studies_export_mica_export_menu_parameters() {
  $param = array(
    'title' => 'Export Studies from Zip Files',
    'weight' => 1
  );
  return $param;
}

function mica_export_find_related_nids($node) {
  $nids = array();
  $nids[] = $node->nid;

  $node_wrapper = entity_metadata_wrapper('node', $node->nid);
  foreach ($node_wrapper->field_investigators->getIterator() as $investigator_wrapper) {
    $nids[] = $investigator_wrapper->nid->value();
  }
  foreach ($node_wrapper->field_contacts_ref->getIterator() as $contact_wrapper) {
    $nids[] = $contact_wrapper->nid->value();
  }

  foreach ($node_wrapper->field_study_populations->getIterator() as $pop_wrapper) {
    $nids[] = $pop_wrapper->nid->value();
    foreach ($pop_wrapper->field_pop_dce->getIterator() as $dce_wrapper) {
      $nids[] = $dce_wrapper->nid->value();
    }
  }
  return $nids;

}

function mica_studies_export_mica_export_to_xml($node, $temp_folder_path) {
  switch ($node->type) {
    case 'study':
      return _mica_export_study_xml($node->nid, $temp_folder_path);
    case 'contact':
      return _mica_export_contact_xml($node->nid);
    case 'population':
      return _mica_export_population_xml($node->nid);
    case 'data_collection_event':
      return _mica_export_dce_xml($node->nid, $temp_folder_path);
    default :
      return NULL;
  }
}

