<?php
/**
 * @file
 * Code for the mica_feature feature.
 */

require_once('mica_feature.features.inc');

/**
 * Implements hook_install().
 */
function mica_feature_install() {
  _mica_import_relations();
  _mica_import_field_groups();
  _mica_import_custom_name_format();
  _mica_fix_menus();
}

function _mica_import_relations() {

  $relation = new MicaRelation();
  $relation->parent_bundle = 'study';
  $relation->child_bundle = 'study_information';
  $relation->label = 'Study » Study Information';
  $relation->options['node_reference'] = 'mica_study_information';
  $relation->options['indexed'] = TRUE;
  $relation->options['child_indexes'] = array('studies_index');
  $relation->options['cascaded'] = TRUE;
  $relation->options['relation'] = 'study_study_information';
  $relation->options['relation_parent_field'] = 'study_information_relation';
  $relation->options['relation_child_field'] = 'study_relation';
  $relation->save();

  $relation = new MicaRelation();
  $relation->parent_bundle = 'study';
  $relation->child_bundle = 'study_files';
  $relation->label = 'Study » Study Files';
  $relation->options['node_reference'] = 'mica_study_files';
  $relation->options['indexed'] = FALSE;
  $relation->options['child_indexes'] = array();
  $relation->options['cascaded'] = TRUE;
  $relation->options['relation'] = 'study_study_files';
  $relation->options['relation_parent_field'] = 'study_files_relation';
  $relation->options['relation_child_field'] = 'study_files';
  $relation->save();
}

function _mica_import_field_groups() {
  module_load_include('inc', 'mica', 'includes/fieldgroups');
  
  // STUDY
  _mica_add_fieldset_group('study','group_details', 'Details', '3', '', array(
    'mica_study_information',
    'mica_study_files',
  ));
  
  // STUDY INFORMATION : GENERAL INFO
  _mica_add_fieldset_group('study_information','group_general_info', 'General Information', '0', '', array(
    'field_full_name',
    'field_investigator',
    'field_contact',
    'field_target_number_participants',
  ));
  
  // STUDY INFORMATION : METHOD
  _mica_add_fieldset_group('study_information','group_method', 'Method', '1', '', array(
    'field_design',
    'field_design_other',
    'field_design_target',
    'field_target_other',
    'field_selection_criteria',
    'field_study_country',
    'field_gender',
    'field_age_min',
    'field_age_max',
    'field_target_number_biosamples',
    'field_biosamples_collected',
    'field_biosamples_collected_other',
    'field_biosamples_tissues',
    'field_gwas_analysis',
    'field_gwas_number',
  ));

  // STUDY INFORMATION : GOVERNANCE
  _mica_add_fieldset_group('study_information','group_governance', 'Governance', '2', '', array(
    'field_access',
    'field_access_other',
  ));

  // STUDY INFORMATION : STATUS
  _mica_add_fieldset_group('study_information','group_status', 'Status', '3', '', array(
    'field_status_start',
    'field_status_end',
  ));
}

function _mica_import_custom_name_format(){
  // add custom field format for name until next release of views
  $custom_format = array(
    'name' => 'Title',
  	'machine_name' => 'title',
  	'format' => 't',
  );
  drupal_write_record('name_custom_format', $custom_format);
} 

function _mica_fix_menus() {
  // fix community path as feature does not support severals menus with same path
  $num_updated = db_update('menu_links')
    ->fields(array(
      'link_path' => '<firstchild>',
      'router_path' => '<firstchild>',
      ))  
    ->condition('menu_name', 'main-menu')
  	->condition('link_title', t('Community'))
  	->execute();
}

