<?php

include_once('mica_opal_harmonization.inc');

/**
 * Implements hook_mica_connector_connection_info().
 */
function mica_opal_mica_connector_connection_info() {
  $connections = array();
  $connections['mica_dataset_opal_connection'] = array(
    'name' => t('Opal'),
    'description' => t('Connection for Opal data repository.'),
    'class' => 'MicaDatasetOpalConnectionClass',
  );
  return $connections;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_opal_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  $links = array();

  switch ($root_path) {

    case 'node/%':
      $node = $router_item['page_arguments'][0];
      if ($node != NULL && $node->type === 'dataset') {

        if (node_access('update', $node)) {
          // add variables
          $links['export-opal'] = array(
            '#theme' => 'menu_local_action',
            '#weight' => 6,
            '#link' => array(
              'title' => t('Export an Opal View'),
              'href' => 'opal-export/node/' . $node->uuid,
            ),
          );
        }
      }
      break;
  }

  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}
