<?php
/**
 * @file
 * Mica Studies Export module
 */

include_once('mica_studies_export_dto_contact.inc');
include_once('mica_studies_export_dto_study.inc');
include_once('mica_studies_export_dto_population.inc');
include_once('mica_studies_export_dto_dce.inc');

/**
 * Implements hook_menu().
 */
function mica_studies_export_dto_menu() {
  $items = array();
  $items['node/%node/export-dto'] = array(
    'title' => 'Export node to Mica-server',
    //  'access callback' => 'mica_export_can_export_node',
    'access arguments' => array(1),
    'page callback' => 'mica_studies_export_dto',
    'page arguments' => array(1),
  );
  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_studies_export_dto_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();
  if ($root_path === 'node/%') {
    $node = $router_item['map']['1'];
    if ($node->type === 'study' && mica_export_can_export_node($node)) {
      $links['export-study-xml'] = array(
        '#theme' => 'menu_local_action',
        '#weight' => 50,
        '#link' => array(
          'title' => t('Export'),
          'href' => 'node/' . $node->nid . '/export-xml'
        ),
      );
      $links['export-study-dto'] = array(
        '#theme' => 'menu_local_action',
        '#weight' => 50,
        '#link' => array(
          'title' => t('Export to mica-server'),
          'href' => 'node/' . $node->nid . '/export-dto'
        ),
      );

    }
  }
  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 *
 */
function mica_studies_export_dto($node) {
  $operations = array();
  if ($node->type == 'study') {

    //get DTO
    $Study_Dto = $node;

    $operations[] = array('_mica_studies_export_dto_study_dto', array($node));

    //Send Dto via REST

    //Send File

  }

  // prepare batch steps
  batch_set(array(
    'operations' => $operations,
    'finished' => 'mica_studies_dto_batch_finished',
  ));
  $redirect = 'node/' . $node->nid;
  batch_process($redirect);
}

function mica_studies_dto_batch_finished() {

}
