<?php
/**
 * @file
 * Mica Studies Export module
 */

include_once('mica_studies_export_dto_contact.inc');
include_once('mica_studies_export_dto_study.inc');
include_once('mica_studies_export_dto_population.inc');
include_once('mica_studies_export_dto_dce.inc');

/**
 * Implements hook_menu().
 */
function mica_studies_export_dto_menu() {
  $items = array();
  $items['node/%node/export-dto'] = array(
    'title' => 'Export node to Mica-server',
    //  'access callback' => 'mica_export_can_export_node',
    'access arguments' => array(1),
    'page callback' => 'mica_studies_export_dto',
    'page arguments' => array(1),
  );
  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_studies_export_dto_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();
  if ($root_path === 'node/%') {
    $node = $router_item['map']['1'];
    if ($node->type === 'study' && mica_export_can_export_node($node)) {
      $links['export-study-xml'] = array(
        '#theme' => 'menu_local_action',
        '#weight' => 50,
        '#link' => array(
          'title' => t('Export'),
          'href' => 'node/' . $node->nid . '/export-xml'
        ),
      );
      $links['export-study-dto'] = array(
        '#theme' => 'menu_local_action',
        '#weight' => 50,
        '#link' => array(
          'title' => t('Export to mica-server'),
          'href' => 'node/' . $node->nid . '/export-dto'
        ),
      );

    }
  }
  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 * Copy attachment files of each node
 */
function mica_studies_copy_attachment_file($documents) {
  $destination = NULL;
  if (empty($documents)) {
    return;
  }

  $path = "/tmp/attachment";
  if (!is_dir($path)) {
    drupal_mkdir($path);
  }
  $destination = $path . "/" . $documents['filename'];
  if (!empty($documents)) {
    file_unmanaged_copy($documents['uri'], $destination, FILE_EXISTS_REPLACE);
  }

  return $destination;
}

function mica_studies_send_attachement($attachement) {
  //@TODO deal with attachement files

  $file_tmp_uri = mica_studies_copy_attachment_file($attachement);
  $file_info = new finfo(FILEINFO_MIME);
  $mime_file = $file_info->file($file_tmp_uri);
//////////////////
  //$url = 'http://198.168.138.210:8082/ws/files/temp'; //ramin
  $url = 'http://localhost:8082/ws/files/temp';
  $cfile = new CurlFile($file_tmp_uri, $mime_file, 'test_file_to_upload');
  $data_file = array('file' => $cfile);
  $resource = curl_init();
  curl_setopt($resource, CURLOPT_URL, $url);
  curl_setopt($resource, CURLOPT_HEADER, TRUE);
  curl_setopt($resource, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($resource, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($resource, CURLINFO_HEADER_OUT, TRUE);
  curl_setopt($resource, CURLOPT_POST, 1);
  curl_setopt($resource, CURLOPT_POSTFIELDS, $data_file);

  $result = curl_exec($resource);

  $http_code = curl_getinfo($resource, CURLINFO_HTTP_CODE);
  $http_header_out = curl_getinfo($resource);

  dpm($http_code);
  // dpm($http_header_out);
  if (preg_match('/(?<=files\/temp\/).*/', $result, $group)) {
    $match = $group[0];
  }
  curl_close($resource);
//
  return $match;
/////////////////////////////////////
}

/**
 *
 */
function mica_studies_export_dto($node) {
  $operations = array();
  if ($node->type == 'study') {

    //get DTO
    $Study_Dto = $node;

    $operations[] = array('_mica_studies_export_dto_study_dto', array($node));

    //Send Dto via REST

    //Send File

  }

  // prepare batch steps
  batch_set(array(
    'operations' => $operations,
    'finished' => 'mica_studies_dto_batch_finished',
  ));
  $redirect = 'node/' . $node->nid;
  batch_process($redirect);
}

function mica_studies_dto_batch_finished() {

}
