<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function mica_opal_view_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
    );
  }
}

/**
 * Implements hook_rest_server_response_formatters_alter().
 */
function mica_opal_view_rest_server_response_formatters_alter(&$formatters) {
  $formatters['xml'] = array(
    'mime types' => array('application/octet-stream'),
    'view' => 'OpalXmlFormatView',
  );
}

/**
 * Implements hook_default_services_endpoint().
 */
function mica_opal_view_default_services_endpoint() {

  $opal_export_endpoint = new stdClass;
  $opal_export_endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $opal_export_endpoint->api_version = 3;
  $opal_export_endpoint->name = 'dataset_variables';
  $opal_export_endpoint->server = 'rest_server';
  $opal_export_endpoint->path = 'opal-export';
  $opal_export_endpoint->authentication = array(
    'services' => 'services',
  );
  $opal_export_endpoint->server_settings = array(
    'rest_server' => array(
      'formatters' => array(
        'xml' => TRUE,
        'bencode' => FALSE,
        'json' => FALSE,
        'jsonp' => FALSE,
        'php' => FALSE,
        'rss' => FALSE,
        'yaml' => FALSE,
      ),
      'parsers' => array(
        'application/json' => TRUE,
        'application/vnd.php.serialized' => FALSE,
        'application/x-www-form-urlencoded' => FALSE,
        'application/x-yaml' => FALSE,
        'multipart/form-data' => FALSE,
      ),
    ),
  );
  $opal_export_endpoint->resources = array(
    'node' => array(
      'operations' => array(
        'retrieve' => array(
          'enabled' => 1,
        ),
      ),
    ),
  );
  $opal_export_endpoint->debug = 0;

  return array($opal_export_endpoint);
}
