<?php

/**
 * Implements hook_help()
 */
function mica_help($path, $arg) {
	switch ($path) {
		case "admin/help#mica":
			return '<p>'.  t("TODO") .'</p>';
			break;
	}
}


/**
 * Implements hook_entity_insert()
 */
function mica_entity_insert($entity, $type) {

	// look for mica_relation with parent type equals saved entity type
	$query = new EntityFieldQuery();
	$result = $query->entityCondition('entity_type', 'node')
	->entityCondition('bundle', 'mica_relation')
	->fieldCondition('parent_type', 'value', $entity->type, '=')
	->execute();

	if (!empty($result['node'])) {
		$keys = array_keys($result['node']);
		$relationId = $keys[0];
		$relation = entity_load('node', $keys);
		$relation = $relation[$relationId];
		$parent = $relation->parent_type[key($relation->parent_type)][0]['value'];
		if($parent == $entity->type) {
			foreach ($relation->child_type[key($relation->child_type)] as $child) {
				// create new child
				$node = new stdClass();
				$node->type = $child['value'];
				node_object_prepare($node);
				$node->title = $entity->title;
				$node->language = $entity->language;
				$node->uid = $entity->uid; // same author
				node_save($node);

				// link this new child node to the parent entity
				$loadedNode = node_load($entity->nid);
				$prop = 'field_'. $child['value'] .'_ref';
				$loadedNode->$prop=array('en' => array(0 => array('nid' => $node->nid,) ,) ,);
				node_save($loadedNode);
			}
		}
	}
}
	