<?php
/**
 * @file
 * Install, update and uninstall functions for the Mica Networks module.
 */

/**
 * Replace built-in node title by title_field.
 */
function mica_networks_update_7500(&$sandbox) {
  module_load_install('mica_core');
  mica_core_replace_titles(array('network'));
}

function mica_networks_access_update_7802(&$update) {
  features_revert(array(
    'mica_networks' => array(
      'field_base',
      'field_instance',
    )
  ));
}