<?php

/**
 * Declare Feeds hook
 */
function mica_opal_ctools_plugin_api($module = '', $api = '') {
  if ($module == "feeds" && $api == "feeds_importer_default") {
    // The current API version is 1.
    return array("version" => 1);
  }
}

/**
 * Implements hook_feeds_importer_default().
 */
function mica_opal_feeds_importer_default() {
  $export = array();

  $feeds_importer = new stdClass;
  $feeds_importer->disabled = FALSE; // Edit this to true to make a default feeds_importer disabled initially
  $feeds_importer->api_version = 1;
  $feeds_importer->id = 'opal_participant_variables';
  $feeds_importer->config = array(
    'name' => 'Participant Variables',
    'description' => '',
    'fetcher' => array(
      'plugin_key' => 'FeedsHTTPSFetcher',
      'config' => array(
        'auto_detect_feeds' => 0,
        'use_pubsubhubbub' => 0,
        'designated_hub' => '',
        'no_verify_peer' => 1,
        'no_verify_host' => 1,
        'use_client_cert' => 1,
        'private_key_file' => 'private://priv.key',
        'client_cert_file' => 'private://client.crt',
      ),
    ),
    'parser' => array(
      'plugin_key' => 'FeedsJSONPathParser',
      'config' => array(
        'context' => '$.*',
        'sources' => array(
          'jsonpath_parser:0' => 'name',
          'jsonpath_parser:1' => 'attributes[?(@[\'name\']==\'label\')].value',
          'jsonpath_parser:2' => 'valueType',
          'jsonpath_parser:3' => 'categories.*.name   categories.*.[name,attributes[?(@[\'name\']==\'label\')].value,name]',
          'jsonpath_parser:4' => 'repeatable',
        ),
        'debug' => array(),
      ),
    ),
    'processor' => array(
      'plugin_key' => 'FeedsNodeProcessor',
      'config' => array(
        'content_type' => 'participant_variable',
        'expire' => '-1',
        'author' => 0,
        'mappings' => array(
          0 => array(
            'source' => 'jsonpath_parser:0',
            'target' => 'title',
            'unique' => FALSE,
          ),
          1 => array(
            'source' => 'jsonpath_parser:1',
            'target' => 'field_label',
            'unique' => FALSE,
          ),
          2 => array(
            'source' => 'jsonpath_parser:2',
            'target' => 'field_value_type',
            'unique' => FALSE,
          ),
          3 => array(
            'source' => 'jsonpath_parser:3',
            'target' => 'field_categories',
            'unique' => FALSE,
          ),
          4 => array(
            'source' => 'jsonpath_parser:4',
            'target' => 'field_repeatable',
            'unique' => FALSE,
          ),
        ),
        'update_existing' => '0',
        'input_format' => 'plain_text',
      ),
    ),
    'content_type' => '',
    'update' => 0,
    'import_period' => '-1',
    'expire_period' => 3600,
    'import_on_create' => 1,
    'process_in_background' => 0,
  );
  $export['opal_participant_variables'] = $feeds_importer;
  return $export;
}