<?php

include_once 'mica_bootstrap_config.features.inc';

/**
 * Implements hook_block_view().
 *
 */
function mica_bootstrap_config_block_view($delta = '') {
  switch ($delta) {
    case 'bootstrap-login':
      return user_is_logged_in() ? NULL : _mica_bootstrap_config_login_block_view();
  }
  return NULL;
}

function _mica_bootstrap_config_login_block_view() {
  return array(
    'subject' => NULL,
    'content' => '<ul class="nav pull-right"><li class="last leaf">' . l(t('Sign in'), 'user/login',array('query' => drupal_get_destination())) . '</li></ul>',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mica_bootstrap_config_form_search_block_form_alter(&$form, $form_state) {
  $form['#attributes']['class'][] = 'navbar-search';
  $form['#attributes']['class'][] = 'pull-left';
  $form['search_block_form']['#title'] = '';
  $form['search_block_form']['#attributes']['class'][] = 'search-query';
  $form['search_block_form']['#attributes']['class'][] = 'span2';
  $form['search_block_form']['#attributes']['placeholder'] = t('Search');
  $form['actions']['submit']['#attributes']['class'][] = 'hide';
}

/**
 * Implements hook_field_group_pre_render()
 */
function mica_bootstrap_config_field_group_pre_render_alter(&$element, $group, &$form) {
  if ($group->format_type === 'div') {
    $element['#prefix'] = str_replace('<h3>', '<h3> <i class="icon-chevron-right"></i> ', $element['#prefix']);
  }
}