<?php
/**
 * @file
 * Mica Import  file
 */

include_once('mica_import_contact.inc');
include_once('mica_import_dce.inc');
include_once('mica_import_population.inc');
include_once('mica_import_study.inc');

function mica_studies_import_mica_import_permission_parameters() {
  return array(
    'import studies' => array(
      'title' => t('Import Studies'),
      'description' => t('Allow users importing studies')
    )
  );
}

function mica_studies_import_mica_import_can_import_node() {
  return user_access('import studies');

}

/**
 * Implements hook_menu().
 */

function mica_studies_import_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path === 'studies') {
    // TODO test if has permission to import
    if (node_access('create', 'study')) {
      $links = array();
      $links['import-xml'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Import XML Studies'),
          'href' => 'import-xml',
        ),
      );
    }
    $data['actions']['output'] = array_merge($data['actions']['output'], $links);
  }
}

function mica_studies_import_mica_import_set_node($dom, $node) {

  switch ($node->type) {
    case 'contact':
      _mica_study_import_get_contact_structure($dom, $node);

      break;
    case 'data-collection-event':
      _mica_study_import_get_dce_structure($dom, $node);

      break;
    case 'population':
      _mica_study_import_get_population_structure($dom, $node);

      break;
    case 'study':
      _mica_study_import_get_study_structure($dom, $node);

      break;

  }

}