<?php

/**
 * @file
 * Code for the Mica Projects feature.
 */

include_once('mica_projects.features.inc');


/**
 * Creates default content after Features successfully installed
 * Implements hook_post_features_rebuild()
 */
function mica_projects_post_features_rebuild() {
  if (!variable_get('mica_projects_features_rebuild_completed', FALSE)) {
    _mica_projects_create_default_content();
    variable_set('mica_projects_features_rebuild_completed', TRUE);
  }
}

function _mica_projects_create_default_content() {
  $research_menu = mica_core_find_menu_for_alias('research');
  $project_menu = mica_core_create_menu(st('Projects'), 'projects', 'projects', FALSE, FALSE, 2, NULL, $research_menu->mlid);

  mica_core_set_menu_option('projects', $project_menu['mlid']);
}

/**
 * Implements hook_form().
 */
function mica_projects_form($node, &$form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_projects_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();

  if ($root_path == 'projects') {
    if (node_access('create', 'project')) {
      $links['add-project'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a Project'),
          'href' => 'node/add/project',
        ),
      );
    }
  }
  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 * Implements hook_insert()
 */
function mica_projects_node_insert($node) {
  if ($node->type === 'project') {
    mica_core_create_node_default_menu($node, TRUE);

    $node->field_teleconferences[LANGUAGE_NONE] = array(
      0 => array(
        'view_id' => 'teleconferences:page',
        'arguments' => $node->nid,
      )
    );
  }
  return;
}

/**
 * Implements hook_field_attach_form()
 */
function mica_projects_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  if ($entity_type == 'node' && $entity->type == 'project') {
    $form['field_teleconferences']['#attributes']['style'] = array('display:none;');
  }
  elseif ($entity_type == 'node' && $entity->type == 'teleconference') {
    // preselect project when specified in the url
    if (isset($_GET['field_project'])) {
      $project_id = $_GET['field_project'];
      if (isset($form['field_project'][LANGUAGE_NONE]['#options'][$project_id])) {
        $form['field_project'][LANGUAGE_NONE]['#value'] = $project_id;
      }
    }
  }
}
