<?php
/**
 * @file
 * Code for the Mica Projects feature.
 */

include_once('mica_projects.features.inc');

/**
 * Implements hook_form().
 */
function mica_projects_form($node, &$form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_projects_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();
  
  if ($root_path == 'projects') {  
    if (node_access('create', 'project')) {
      $node_type = node_type_load('project');
      $links['add-project'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a !name', array('!name' => $node_type->name)),
          'href' => 'node/add/project',
        ),
      );
    } 
  }
  /*elseif ($root_path == 'node/%') {
    if (node_access('create', 'teleconference')) {
      $node = node_load($router_item['page_arguments'][0]->nid);
      if ($node != NULL && $node->type == 'project') {
        $node_type = node_type_load('teleconference');
        $href = url('node/add/teleconference', array('query' => array('field_project' => $node->nid)));
        $links['add-teleconference'] = array(
          '#theme' => 'menu_local_action',
          '#link' => array(
            'title' => t('<a href="@url">Add a !name</a>', array('!name' => $node_type->name, '@url' => $href)),
            'localized_options' => array('html' => TRUE),
          ),
        );
      }
    }
  }*/
  
  
  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 * Implements hook_node_insert()
 */
function mica_projects_insert(&$node) {
  if ($node->type === 'project') {
    $node->field_teleconferences['und'] = array(
      0 => array(
        'view_id' => 'teleconferences:page',
        'arguments' => $node->nid,
      )
    );
  }  
  return;
}

/**
 * Implements hook_field_attach_form()
 */
function mica_projects_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  if ($entity_type == 'node' && $entity->type == 'project') {
    $form['field_teleconferences']['#attributes']['style'] = array('display:none;');
  }
  elseif ($entity_type == 'node' && $entity->type == 'teleconference') {
    // preselect project when specified in the url
    if (isset($_GET['field_project'])) {
      $project_id = $_GET['field_project'];
      if (isset($form['field_project'][LANGUAGE_NONE]['#options'][$project_id])) {
        $form['field_project'][LANGUAGE_NONE]['#value'] = $project_id;
      }
    }
  }
}
