<?php
/**
 * @file
 * Code for the mica_devel feature.
 */

include_once('mica_devel.features.inc');

function mica_devel_menu() {
	$items['admin/config/development/mica'] = array(
    'title' => 'Mica',
    'description' => 'development tools for Mica',
  	'page callback' => 'drupal_get_form',
    'page arguments' => array('_mica_devel_dummy_form'),
    'access arguments' => array('administer site configuration'),
	);
	return $items;
}

function _mica_devel_dummy_form() {
	$form['dummy']['description'] = array(
  	'#markup' => '<p>' . t('Form example to run custom actions') . '</p>',
	);
	$form['dummy']['run'] = array(
    '#type' => 'submit',
    '#value' => t('Run dummy method'),
    '#submit' => array('_mica_devel_dummy_run'),
	);
	$form['taxonomy_import']['description'] = array(
	  	'#markup' => '<p>' . t('Import all taxonomies') . '</p>',
	);
	$form['taxonomy_import']['run'] = array(
	    '#type' => 'submit',
	    '#value' => t('Run taxonomy import'),
	    '#submit' => array('_mica_devel_import_taxonomies_run'),
	);
	$form['taxonomy_delete']['description'] = array(
		  	'#markup' => '<p>' . t('Delete all taxonomies') . '</p>',
	);
	$form['taxonomy_delete']['run'] = array(
		    '#type' => 'submit',
		    '#value' => t('Run taxonomy delete'),
		    '#submit' => array('_mica_devel_delete_taxonomies'),
	);
	return $form;
}

function _mica_devel_dummy_run() {
  
}

function _mica_devel_delete_taxonomies(){
  $taxonomies = taxonomy_vocabulary_get_names();
  
  foreach(_mica_datasets_taxonomies() as $dimensions){
    $machine_name = substr($dimensions[0], 0, strlen($dimensions[0]) - 4);
    drupal_set_message("Deleting $machine_name");
  	taxonomy_vocabulary_delete($taxonomies[$machine_name]->vid);
  }
}
function _mica_devel_import_taxonomies_run() {
	foreach(_mica_datasets_taxonomies() as $taxonomy){
	  $machine_name = substr($taxonomy[0], 0, strlen($taxonomy[0]) - 4);
	  drupal_set_message("Importing $machine_name");
		_mica_datasets_taxonomy_import($taxonomy[0], $taxonomy[1]);
	}
}
