<?php

/**
 * Implements hook_help()
 */
function mica_help($path, $arg) {
  switch ($path) {
    case "admin/help#mica":
      return '<p>' //
        . t("Mica Documentation can be found here:") . '</p>' //
        . '<ul>' //
        . ' <li><a href="http://wiki.obiba.org/display/MICADOC/Mica+Administration+Guide">' . t('Mica Administration Guide') . '</a></li>' //
        . ' <li><a href="http://wiki.obiba.org/display/MICADOC/Mica+User+Guide">' . t('Mica User Guide') . '</a></li>' //
        . '</ul>';
      break;
  }
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function mica_block_info() {
  $blocks = array();
  $blocks['powered-by-mica'] = array(
    'info' => t('Powered by Mica'),
    'weight' => '10',
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['mica-search-filters'] = array(
    'info' => t('Search filters selection'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'studies-search',
  );
  $blocks['mica-search'] = array(
    'info' => t('Search'),
    'status' => FALSE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function mica_block_view($delta = '') {
  module_load_include('inc', 'mica', 'includes/blocks');

  global $user;
  $block = array();
  switch ($delta) {
    case 'powered-by-mica':
      $block['subject'] = NULL;
      $block['content'] = '<span>' . t('Powered by <a href="@poweredby">Mica</a>', array('@poweredby' => 'http://obiba.org')) . '</span>';
      break;

    case 'mica-search':
      $block['subject'] = t('Search');
      $block['content'] = mica_search_block_content();
      return $block;

    case 'mica-search-filters':
      if ($user->uid == 0) {
        return; // not available for anonymous user
      }
      $block['subject'] = t('Search filters selection');
      $content = mica_search_filters_block_content();
      if ($content) {
        $block['content'] = $content;
        return $block;
      }
      return;
  }
  return $block;
}

