<?php

/**
 * Implements hook_help().
 */
function mica_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mica':
      return '<p>' . t('Mica Documentation can be found here:') . '</p>'
        . '<ul>'
        . ' <li><a href="http://wiki.obiba.org/display/MICADOC/Mica+Administration+Guide">' . t('Mica Administration Guide') . '</a></li>'
        . ' <li><a href="http://wiki.obiba.org/display/MICADOC/Mica+User+Guide">' . t('Mica User Guide') . '</a></li>'
        . '</ul>';
  }
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function mica_block_info() {
  $blocks = array();
  $blocks['powered-by-mica'] = array(
    'info' => t('Powered by Mica'),
    'weight' => '10',
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['mica-search-filters'] = array(
    'info' => t('Search filters selection'),
    'status' => TRUE,
    'region' => BLOCK_REGION_NONE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'studies-search',
    'weight' => '1000',
  );
  $blocks['mica-search'] = array(
    'info' => t('Search'),
    'status' => FALSE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function mica_block_view($delta = '') {
  module_load_include('inc', 'mica', 'includes/mica_blocks');

  global $user;
  $block = array();
  switch ($delta) {
    case 'powered-by-mica':
      $info = drupal_parse_info_file(drupal_get_path('module', 'mica_core') . '/mica_core.info');
      $version = isset($info['version']) ? str_replace('7.x-', '', $info['version']) : 'dev';
      $block['subject'] = NULL;
      $block['content'] = '<span>'
        . t('Powered by <a href="@poweredby">Mica @version</a>',
          array(
            '@poweredby' => 'http://obiba.org/node/174',
            '@version' => $version
          )
        )
        . '</span>';
      return $block;

    case 'mica-search':
      $block['subject'] = t('Search');
      $block['content'] = mica_search_block_content();
      return $block;

    case 'mica-search-filters':
      if ($user->uid == 0) {
        return NULL; // not available for anonymous user
      }
      $block['subject'] = t('Search filters selection');
      $content = mica_search_filters_block_content();
      if ($content) {
        $block['content'] = $content;
        return $block;
      }
  }
  return $block;
}

/**
 * Implements hook_preprocess_block().
 */
function mica_preprocess_block(&$variables) {
  // add block-facetapi css class to search-filters block
  if ($variables['block']->module === 'mica' && $variables['block']->delta === 'mica-search-filters') {
    $variables['classes_array'][] = 'block-facetapi';
  }
}