<?php

/**
 * @file
 * Code for the Mica Community feature.
 */

include_once('mica_community.features.inc');

/**
 * Creates default content after Features successfully installed
 * Implements hook_post_features_rebuild().
 */
function mica_community_post_features_rebuild() {
  if (!variable_get('mica_community_features_rebuild_completed', FALSE)) {
    _mica_community_create_default_content();
    variable_set('mica_community_features_rebuild_completed', TRUE);
  }
}

function _mica_community_create_default_content() {
  // Create static page Community
  $community_content = file_get_contents(drupal_get_path('module', 'mica_community') . '/default_data/community.html');
  $page = mica_core_add_page(st('Community'), st($community_content), 'community-overview', 'bootstrap');
  if ($page) {
    _mica_community_build_menu_from_node($page);
  }
}

function _mica_community_build_menu_from_node($page) {
  $community_menu = mica_core_create_menu(st('Community'), "node/$page->nid", '', FALSE, TRUE, 45);

  if (!empty($community_menu)) {
    mica_core_create_menu(st('News'), 'news', 'news', FALSE, FALSE, 10, NULL, $community_menu['mlid']);

    mica_core_create_menu(st('Forums'), 'forum', 'forum', FALSE, FALSE, 11, NULL, $community_menu['mlid']);
    if (!empty($forum_menu) && empty($forum_menu['exist'])) {
      mica_core_set_menu_option('forum', $forum_menu['mlid']);
    }

    mica_core_create_menu(st('Blogs'), 'blog', 'blog', FALSE, FALSE, 12, NULL, $community_menu['mlid']);
    if (!empty($blog_menu) && empty($blog_menu['exist'])) {
      mica_core_set_menu_option('blog', $blog_menu['mlid']);
    }

    $event_menu = mica_core_create_menu(st('Events'), 'events', 'events', FALSE, TRUE, 13, NULL, $community_menu['mlid']);
    if (!empty($event_menu)) {
      mica_core_create_menu(st('All Events'), 'events', 'events', FALSE, FALSE, 1, NULL, $event_menu['mlid']);
      mica_core_create_menu(st('Calendar'), 'calendar-field-event-date/year', 'calendar-field-event-date/year', FALSE, FALSE, 0, NULL, $event_menu['mlid']);
      mica_core_set_menu_option('event', $event_menu['mlid']);
    }
  }

  $research_menu = mica_core_find_menu_for_alias('research');
  if (isset($research_menu)) {
    $publication_menu = mica_core_create_menu(st('Publications'), 'publications', 'publications', FALSE, FALSE, 10, NULL, $research_menu->mlid);
    if (!empty($publication_menu) && empty($publication_menu['exist'])) {
      mica_core_set_menu_option('publication', $publication_menu['mlid']);
    }
  }

}

/**
 * Creates default content in mica core installation
 * Implements hook_mica_create_default_menu_module()
 */
function mica_community_create_default_menu_module() {
  $page = _mica_core_get_node_by_url_alias('community-overview');
  if ($page) {
    _mica_community_build_menu_from_node($page);
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_community_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();

  if ($root_path === 'community') {
    if (node_access('create', 'contact')) {
      $links['add-contact'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a Contact'),
          'href' => 'node/add/contact',
        ),
      );
    }
  }
  elseif ($root_path === 'events') {
    if (node_access('create', 'event')) {
      $links['add-event'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add an Event'),
          'href' => 'node/add/event',
        ),
      );
    }
  }
  elseif ($root_path === 'publications') {
    if (node_access('create', 'publication')) {
      $links['add-publication'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a Publication'),
          'href' => 'node/add/publication',
        ),
      );
    }
  }

  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 * Implements hook_node_insert().
 */
function mica_community_node_insert($node) {
  if ($node->type === 'publication' || $node->type === 'event') {
    mica_core_create_node_default_menu($node, TRUE);
  }
}

function mica_community_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'forum':

      $vid = variable_get('forum_nav_vocabulary', 0);
      $vocabulary = taxonomy_vocabulary_load($vid);
      if (_forum_node_check_node_type($node)) {
        if ($view_mode == 'full' && node_is_page($node)) {
          // Breadcrumb navigation
          $breadcrumb[] = l(t('Home'), NULL);
          $breadcrumb[] = l(t('Community'), 'community');
          $breadcrumb[] = l($vocabulary->name, 'forum');
          if ($parents = taxonomy_get_parents_all($node->forum_tid)) {
            $parents = array_reverse($parents);
            foreach ($parents as $parent) {
              $breadcrumb[] = l($parent->name, 'forum/' . $parent->tid);
            }
          }
          drupal_set_breadcrumb($breadcrumb);

        }
      }
      break;
    case 'blog':
      if ($view_mode == 'full' && node_is_page($node)) {
        $breadcrumb[] = l(t('Home'), NULL);
        $breadcrumb[] = l(t('Community'), 'community');
        $breadcrumb[] = l(t('Blogs'), 'blog');

        drupal_set_breadcrumb($breadcrumb);
      }
      break;
  }
}
