<?php

/**
 * @file
 * Install, update and uninstall functions for the Mica Community module.
 */

/**
 * Implements hook_install().
 */
function mica_community_install() {
  mica_core_configure_feeds_tamper('mica_community');
}

/**
 * Updates the mica_community fields
 */
function mica_community_update_7120() {
  features_revert(array('mica_community' => array('field', 'menu_links')));
  mica_core_configure_feeds_tamper('mica_community');
}

