<?php
/**
 * @file
 * Code for the Mica Community feature.
 */

include_once('mica_community.features.inc');

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_community_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();
  
  if ($root_path == 'community') {  
    if (node_access('create', 'contact')) {
      $links['add-contact'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a Contact'),
          'href' => 'node/add/contact',
        ),
      );
    }
    if (node_access('create', 'institution')) {
      $links['add-institution'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add an Institution'),
          'href' => 'node/add/institution',
        ),
      );
    } 
  }
  elseif ($root_path == 'events') {
    if (node_access('create', 'event')) {
      $links['add-event'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add an Event'),
          'href' => 'node/add/event',
        ),
      ); 
    }
  }
  elseif ($root_path == 'publications') {
    if (node_access('create', 'publication')) {
      $links['add-publication'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a Publication'),
          'href' => 'node/add/publication',
        ),
      ); 
    }
  }
  
  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
* Implements hook_node_insert()
*/
function mica_community_node_insert($node) {
	if ($node->type === 'publication' || $node->type === 'event') {
		mica_core_create_menu($node, 1);
	}
}
