<?php
/**
 * @file
 * Mica Studies Export module
 */

include_once('mica_studies_export_json_contact.inc');
include_once('mica_studies_export_json_study.inc');
include_once('mica_studies_export_json_population.inc');
include_once('mica_studies_export_json_dce.inc');
include_once('mica_studies_export_json_dataset.inc');
include_once('mica_studies_export_json_network.inc');

/**
 * Implements hook_menu().
 */
function mica_studies_export_json_menu() {
  $items = array();
  $items['node/%node/export-dto'] = array(
    'title' => 'Export node to Mica-server',
    //  'access callback' => 'mica_export_can_export_node',
    'access arguments' => array(1),
    'page callback' => 'mica_studies_export_json',
    'page arguments' => array(1),
  );
  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_studies_export_json_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();
  if ($root_path === 'node/%') {
    $node = $router_item['map']['1'];
    if ($node->type === 'study' && mica_export_can_export_node($node)) {
      $links['export-study-xml'] = array(
        '#theme' => 'menu_local_action',
        '#weight' => 50,
        '#link' => array(
          'title' => t('Export'),
          'href' => 'node/' . $node->nid . '/export-xml'
        ),
      );
      $links['export-study-dto'] = array(
        '#theme' => 'menu_local_action',
        '#weight' => 50,
        '#link' => array(
          'title' => t('Export to mica-server'),
          'href' => 'node/' . $node->nid . '/export-dto'
        ),
      );

    }
  }
  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 *
 */
function mica_studies_export_json($node) {
  $operations = array();
  if ($node->type == 'study') {

    //get DTO

    $operations[] = array('_mica_studies_export_json_study_dto', array($node));

    $operations[] = array('_mica_studies_export_json_dataset_dto', array($node));

    $operations[] = array('_mica_studies_export_json_network_dto', array($node));

    $operations[] = array('_mica_studies_export_json_save_json_file', array());
    //Send Dto via REST

    //Send File

  }

  // prepare batch steps
  batch_set(array(
    'operations' => $operations,
    'finished' => 'mica_studies_dto_batch_finished',
  ));
  $redirect = 'node/' . $node->nid;
  batch_process($redirect);
}

/**
 * Create tmp folder
 */
function _mica_studies_export_json_create_tmp_folder($folder_name) {
  $tmp_folder_name = file_directory_temp() . '/' . $folder_name;
  drupal_mkdir($tmp_folder_name);
  return $tmp_folder_name;
}

function _mica_studies_export_json_temp_attachement_folder($tmp_folder_root) {
  $attachment_temp_folder = $tmp_folder_root . '/attachments/';
  if (!is_dir($attachment_temp_folder)) {
    drupal_mkdir($tmp_folder_root . '/attachments/');
  }
  return $attachment_temp_folder;
}

function _mica_studies_export_json_save_json_file(&$context) {
  global $user;

  $tmp_folder_root = _mica_studies_export_json_create_tmp_folder(str_replace(' ', '_', $context['results']['study']['title_study']));
  //save study json
  $tmp_file_study_name = $tmp_folder_root . '/' . 'study-' . $context['results']['study']['uuid'];
  file_unmanaged_save_data($context['results']['study']['study_json'], $tmp_file_study_name . '.json', FILE_EXISTS_RENAME);

  if (!empty($context['results']['study']['attachments'])) {
    foreach ($context['results']['study']['attachments'] as $attachment) {
      $attachment_temp_folder = _mica_studies_export_json_temp_attachement_folder($tmp_folder_root);
      file_unmanaged_copy($attachment['uri'], $attachment_temp_folder . $attachment['uuid']);
    }
  }

  if (!empty($context['results']['dce']['attachments'])) {
    foreach ($context['results']['dce']['attachments'] as $dce) {
      foreach ($dce as $attachment) {
        $attachment_temp_folder = _mica_studies_export_json_temp_attachement_folder($tmp_folder_root);
        file_unmanaged_copy($attachment['uri'], $attachment_temp_folder . $attachment['uuid']);
      }
    }
  }

  foreach ($context['results']['datasets'] as $dataset) {
    $tmp_file_root_dataset_name = $tmp_folder_root . '/' . 'dataset-' . $dataset['uuid'];
    file_unmanaged_save_data($dataset['dataset_json'], $tmp_file_root_dataset_name . '.json', FILE_EXISTS_RENAME);
  }

  foreach ($context['results']['networks'] as $key_network => $network) {
    if (is_int($key_network)) {
      $tmp_file_root_network_name = $tmp_folder_root . '/' . 'network-' . $network['uuid'];
      file_unmanaged_save_data($network['network_json'], $tmp_file_root_network_name . '.json', FILE_EXISTS_RENAME);
    }
  }

  if (!empty($context['results']['networks']['attachments'])) {
    foreach ($context['results']['networks']['attachments'] as $attachment) {
      $attachment_temp_folder = _mica_studies_export_json_temp_attachement_folder($tmp_folder_root);
      file_unmanaged_copy($attachment['uri'], $attachment_temp_folder . $attachment['uuid']);
    }
  }

  $zip_file_to_download = mica_studies_export_json_create_zip_file($tmp_folder_root, $context['results']['study']['title_study']);
  //delete temp files
  if (!empty($tmp_folder_root)) {
    recurseRmdir($tmp_folder_root);
  }

  drupal_set_message(
    t("<a href='@file_url'>Download exported study zip file.</a> This file is also available in your <a href='@file_manager_url'>File manager</a>",
      array(
        '@file_url' => file_create_url($zip_file_to_download),
        '@file_manager_url' => url('user/' . $user->uid . '/imce')
      )),
    'status');
}

function recurseRmdir($dir) {
  $files = array_diff(scandir($dir), array('.', '..'));
  foreach ($files as $file) {
    (is_dir("$dir/$file")) ? recurseRmdir("$dir/$file") : unlink("$dir/$file");
  }
  return rmdir($dir);
}

function mica_studies_export_json_create_zip_file($folder_to_zip, $name_zip_file) {
  global $user;

  //Archive the files
  $name_zip_file = drupal_strtolower(str_replace(' ', '_', $name_zip_file));
  //create public drupal folder if not exist
  $public_folder_drupal = drupal_realpath('public:///' . $user->name . '/export-mica-server/');

  if (!is_dir($public_folder_drupal)) {
    drupal_mkdir($public_folder_drupal);
  }
  $zip_file_path = $public_folder_drupal . '/' . $name_zip_file . '-' . date('Y-m-d_H_m_s', time()) . '.zip';

  //retrieve files in directory to archive
  $scanned_directory = array_diff(scandir($folder_to_zip), array('..', '.'));
  fopen($zip_file_path, 'w');
  $zip = new ZipArchive;
  $zip->open($zip_file_path);
  foreach ($scanned_directory as $file) {
    if (is_dir($folder_to_zip . '/' . $file)) {
      $scanned_subdirectory = array_diff(scandir($folder_to_zip . '/' . $file), array('..', '.'));
      $zip->addEmptyDir($file);
      foreach ($scanned_subdirectory as $subfile) {
        $zip->addFile($folder_to_zip . '/' . $file . '/' . $subfile, $name_zip_file . '/' . $file . '/' . $subfile);
      }
    }
    else {
      $zip->addFile($folder_to_zip . '/' . $file, $name_zip_file . '/' . $file);
    }
  }
  fclose($zip_file_path);

  return 'public:///' . $user->name . '/export-mica-server/' . $name_zip_file . '-' . date('Y-m-d_H_m_s', time()) . '.zip';
}

function mica_studies_dto_batch_finished() {

}
