#
# Generated by
#   drush pm-list --pipe --no-core --type=theme
#   drush pm-list --pipe --no-core --type=module
#

mica-delete-7.0: mica-delete-module-7.0
	# don't delete themes in case they were overridden
	$(call delete-profile,mica_standard) && \
	$(call delete-profile,mica_distribution) && \
	$(call delete-profile,mica_demo)

mica-delete-module-7.0:
	$(call delete-module,acl) && \
	$(call delete-module,content_access) && \
	$(call delete-module,content_access_rules) && \
	$(call delete-module,forum_access) && \
	$(call delete-module,actions_permissions) && \
	$(call delete-module,multiselect) && \
	$(call delete-module,bulk_export) && \
	$(call delete-module,ctools) && \
	$(call delete-module,ctools_ajax_sample) && \
	$(call delete-module,ctools_plugin_example) && \
	$(call delete-module,ctools_custom_content) && \
	$(call delete-module,ctools_access_ruleset) && \
	$(call delete-module,page_manager) && \
	$(call delete-module,stylizer) && \
	$(call delete-module,views_content) && \
	$(call delete-module,calendar) && \
	$(call delete-module,date) && \
	$(call delete-module,date_all_day) && \
	$(call delete-module,date_api) && \
	$(call delete-module,date_context) && \
	$(call delete-module,date_migrate) && \
	$(call delete-module,date_popup) && \
	$(call delete-module,date_repeat) && \
	$(call delete-module,date_repeat_field) && \
	$(call delete-module,date_tools) && \
	$(call delete-module,date_views) && \
	$(call delete-module,graphapi_demo) && \
	$(call delete-module,devel) && \
	$(call delete-module,devel_generate) && \
	$(call delete-module,graphapi_devel) && \
	$(call delete-module,devel_node_access) && \
	$(call delete-module,multiselect_fapi_example) && \
	$(call delete-module,variable_example) && \
	$(call delete-module,date_migrate_example) && \
	$(call delete-module,features) && \
	$(call delete-module,features_override) && \
	$(call delete-module,feeds) && \
	$(call delete-module,feeds_ui) && \
	$(call delete-module,feeds_import) && \
	$(call delete-module,feeds_news) && \
	$(call delete-module,feeds_tamper) && \
	$(call delete-module,feeds_tamper_ui) && \
	$(call delete-module,content_taxonomy) && \
	$(call delete-module,content_taxonomy_autocomplete) && \
	$(call delete-module,content_taxonomy_migrate) && \
	$(call delete-module,email) && \
	$(call delete-module,field_display_label) && \
	$(call delete-module,field_permissions) && \
	$(call delete-module,field_group) && \
	$(call delete-module,link) && \
	$(call delete-module,name) && \
	$(call delete-module,node_reference) && \
	$(call delete-module,noderefcreate) && \
	$(call delete-module,references) && \
	$(call delete-module,cck_select_other) && \
	$(call delete-module,title) && \
	$(call delete-module,user_reference) && \
	$(call delete-module,viewreference) && \
	$(call delete-module,smtp) && \
	$(call delete-module,imce) && \
	$(call delete-module,mica) && \
	$(call delete-module,node_reference_block) && \
	$(call delete-module,potx) && \
	$(call delete-module,entity_translation) && \
	$(call delete-module,entity_translation_upgrade) && \
	$(call delete-module,lang_dropdown) && \
	$(call delete-module,l10n_update) && \
	$(call delete-module,i18n_block) && \
	$(call delete-module,i18n_contact) && \
	$(call delete-module,facetapi_i18n) && \
	$(call delete-module,i18n_field) && \
	$(call delete-module,i18n) && \
	$(call delete-module,languageicons) && \
	$(call delete-module,i18n_menu) && \
	$(call delete-module,i18n_node) && \
	$(call delete-module,i18n_forum) && \
	$(call delete-module,i18n_select) && \
	$(call delete-module,i18n_path) && \
	$(call delete-module,i18n_string) && \
	$(call delete-module,i18n_sync) && \
	$(call delete-module,i18n_taxonomy) && \
	$(call delete-module,i18n_redirect) && \
	$(call delete-module,i18n_translation) && \
	$(call delete-module,i18n_variable) && \
	$(call delete-module,advanced_help) && \
	$(call delete-module,help_example) && \
	$(call delete-module,auto_entitylabel) && \
	$(call delete-module,auto_nodetitle) && \
	$(call delete-module,chain_menu_access) && \
	$(call delete-module,corresponding_node_references) && \
	$(call delete-module,diff) && \
	$(call delete-module,entity) && \
	$(call delete-module,entity_token) && \
	$(call delete-module,google_fonts) && \
	$(call delete-module,image_url_formatter) && \
	$(call delete-module,job_scheduler) && \
	$(call delete-module,job_scheduler_trigger) && \
	$(call delete-module,less) && \
	$(call delete-module,less_demo) && \
	$(call delete-module,libraries) && \
	$(call delete-module,logintoboggan) && \
	$(call delete-module,logintoboggan_content_access_integration) && \
	$(call delete-module,logintoboggan_rules) && \
	$(call delete-module,logintoboggan_variable) && \
	$(call delete-module,mail_edit) && \
	$(call delete-module,masquerade) && \
	$(call delete-module,menu_breadcrumb) && \
	$(call delete-module,menu_firstchild) && \
	$(call delete-module,menu_view_unpublished) && \
	$(call delete-module,module_filter) && \
	$(call delete-module,password_policy_password_tab) && \
	$(call delete-module,password_policy) && \
	$(call delete-module,pathauto) && \
	$(call delete-module,progress) && \
	$(call delete-module,strongarm) && \
	$(call delete-module,token) && \
	$(call delete-module,panels_mini) && \
	$(call delete-module,panels_node) && \
	$(call delete-module,panels) && \
	$(call delete-module,panels_ipe) && \
	$(call delete-module,view_unpublished) && \
	$(call delete-module,search_api) && \
	$(call delete-module,search_api_combined) && \
	$(call delete-module,search_api_facetapi) && \
	$(call delete-module,search_api_page) && \
	$(call delete-module,search_api_ranges) && \
	$(call delete-module,search_api_views) && \
	$(call delete-module,search_api_solr) && \
	$(call delete-module,current_search) && \
	$(call delete-module,facetapi) && \
	$(call delete-module,services) && \
	$(call delete-module,xcal_format) && \
	$(call delete-module,services_oauth) && \
	$(call delete-module,http_client) && \
	$(call delete-module,http_client_oauth) && \
	$(call delete-module,rest_server) && \
	$(call delete-module,xmlrpc_server) && \
	$(call delete-module,captcha) && \
	$(call delete-module,image_captcha) && \
	$(call delete-module,recaptcha) && \
	$(call delete-module,recaptcha_mailhide) && \
	$(call delete-module,googleanalytics) && \
	$(call delete-module,taxonomy_csv) && \
	$(call delete-module,taxonomy_manager) && \
	$(call delete-module,autocomplete_deluxe) && \
	$(call delete-module,ckeditor) && \
	$(call delete-module,collapsiblock) && \
	$(call delete-module,jquery_update) && \
	$(call delete-module,superfish) && \
	$(call delete-module,variable) && \
	$(call delete-module,variable_admin) && \
	$(call delete-module,variable_advanced) && \
	$(call delete-module,variable_realm) && \
	$(call delete-module,variable_store) && \
	$(call delete-module,variable_views) && \
	$(call delete-module,views) && \
	$(call delete-module,views_bulk_operations) && \
	$(call delete-module,views_data_export) && \
	$(call delete-module,views_ui) && \
	$(call delete-module,graphapi) && \
	$(call delete-module,graph_phyz) && \
	$(call delete-module,graphviz) && \
	$(call delete-module,graphapi_relation) && \
	$(call delete-module,workbench) && \
	$(call delete-module,workbench_moderation)


mica-delete-7.0-dev: mica-delete-7.0
mica-delete-7.0-rc1: mica-delete-7.0
mica-delete-7.0-rc2: mica-delete-7.0
mica-delete-7.0-rc3: mica-delete-7.0
mica-delete-7.0-rc4: mica-delete-7.0



