<?php
/**
 * @file
 * Code for the mica_studies feature.
 */

require_once('mica_studies.features.inc');

/**
 * Implements hook_install().
 */
function mica_studies_install() {
  _mica_import_relations();
  _mica_import_field_groups();
  _mica_import_custom_name_format();
  _mica_node_reference_block();
}

/**
 * Implements hook_menu().
 */
function mica_studies_menu() {
  $items = array();
  $items['export'] = array(
    'title' => 'Export',
    'page callback' => 'mica_studies_export_page',
    'access callback' => 'mica_studies_export_page_access',
    'file' => 'mica_studies.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mica_studies_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  $links = array();

  if ($root_path == 'studies') {
    if (node_access('create', 'study')) {
      $node_type = node_type_load('study');
      $links['add-study'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add a !name', array('!name' => $node_type->name)),
          'href' => 'node/add/study',
      ),
      );
    }
  }
  elseif ($root_path == 'documents') {
    $links = array();
    if (node_access('create', 'documents')) {
      $links['add-documents'] = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => t('Add some Documents'),
          'href' => 'node/add/documents',
      ),
      );
    }
  }

  $data['actions']['output'] = array_merge($data['actions']['output'], $links);
}

/**
 * Implements feeds_permission().
 */
function mica_studies_permission() {
  $perms = array(
    'export data' => array(
      'title' => t('Export Data'),
      'description' => t('Allow exportation of data.')
  ),
  );
  return $perms;
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function mica_studies_block_info() {
  $blocks['mica-search-filters'] = array(
    'info' => t('Search filters selection'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'studies-search',
  );

  $blocks['mica-studies-search'] = array(
    'info' => t('Studies search'),
    'status' => TRUE,
    'region' => BLOCK_REGION_NONE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/*
studies', // line separated paths
  );

  $blocks['mica-search'] = array(
    'info' => t('Search'),
    'status' => TRUE,
    'region' => BLOCK_REGION_NONE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function mica_studies_block_view($delta = '') {
  global $user;
  $block = array();

  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'mica-search':
      module_load_include('inc', 'mica', 'includes/blocks');
      $block['subject'] = t('Search');
      $block['content'] = mica_search_block_content();
      return $block;
    case 'mica-studies-search':
      module_load_include('inc', 'mica', 'includes/blocks');
      $block['subject'] = t('Studies search');
      $content = mica_search_api_block_content('studies-search', t('Enter the terms you wish to search for in studies.'));

      if ($content) {
        $block['content'] = $content;
        return $block;
      }
      else {
        // no content, then no block
        return;
      }
    case 'mica-search-filters':
      if ($user->uid == 0) {
        // not available for anonymous user
        return;
      }

      module_load_include('inc', 'mica', 'includes/blocks');
      $block['subject'] = t('Search filters selection');
      $content = mica_search_filters_block_content();

      if ($content) {
        $block['content'] = $content;
        return $block;
      }
      else {
        // no content, then no block
        return;
      }
    default:
      return;
  }

}

/**
 * Menu access callback.
 */
function mica_studies_export_page_access() {
  return user_access('export data');
}

function _mica_import_relations() {

  $relation = new MicaRelation();
  $relation->parent_bundle = 'study';
  $relation->child_bundle = 'study_information';
  $relation->label = 'Study » Study Information';
  $relation->options['node_reference'] = 'mica_study_information';
  $relation->options['indexed'] = TRUE;
  $relation->options['child_indexes'] = array('studies_index');
  $relation->options['cascaded'] = TRUE;
  $relation->options['relation'] = 'study_study_information';
  $relation->options['relation_parent_field'] = 'study_information_relation';
  $relation->options['relation_child_field'] = 'study_relation';
  $relation->save();

  $relation = new MicaRelation();
  $relation->parent_bundle = 'study';
  $relation->child_bundle = 'study_documents';
  $relation->label = 'Study » Study Documents';
  $relation->options['node_reference'] = 'mica_study_documents';
  $relation->options['indexed'] = FALSE;
  $relation->options['child_indexes'] = array();
  $relation->options['cascaded'] = TRUE;
  $relation->options['relation'] = 'study_study_documents';
  $relation->options['relation_parent_field'] = 'study_documents_relation';
  $relation->options['relation_child_field'] = 'study_documents';
  $relation->save();
}

function _mica_import_field_groups() {
  module_load_include('inc', 'mica', 'includes/fieldgroups');

  // STUDY: GENERAL INFO
  _mica_add_fieldset_group('study','group_general_info', 'General Information', '2', '', array(
    'field_full_name',
    'field_website',
    'field_investigator',
    'field_contact',
    'field_target_number_participants',
    'field_target_number_biosamples',
    'field_p3g_observatory_link',
  ));

  // STUDY
  _mica_add_fieldset_group('study','group_details', 'Details', '3', '', array(
    'mica_study_information',
    'mica_study_documents',
  ));

  // STUDY INFORMATION : METHOD
  _mica_add_fieldset_group('study_information','group_method', 'Method', '1', '', array(
    'field_design',
    'field_design_other',
    'field_design_target',
    'field_target_other',
    'field_selection_criteria',
    'field_study_country',
    'field_gender',
    'field_age_min',
    'field_age_max',
    'field_biosamples_collected',
    'field_biosamples_collected_other',
    'field_biosamples_tissues',
    'field_gwas_analysis',
    'field_gwas_number',
  ));

  // STUDY INFORMATION : GOVERNANCE
  _mica_add_fieldset_group('study_information','group_governance', 'Governance', '2', '', array(
    'field_access',
    'field_access_other',
  ));

  // STUDY INFORMATION : STATUS
  _mica_add_fieldset_group('study_information','group_status', 'Status', '3', '', array(
    'field_status_start',
    'field_status_end',
  ));
}

function _mica_import_custom_name_format(){
  // add custom field format for name until next release of views
  $custom_format = array(
    'name' => 'Title',
  	'machine_name' => 'title',
  	'format' => 't',
  );
  drupal_write_record('name_custom_format', $custom_format);
}

function _mica_node_reference_block() {
  db_delete('block_node_type')
  ->condition('module', 'node_reference_block')
  ->condition('delta', 'related-content')
  ->condition('type', 'study%','LIKE')
  ->execute();
  $query = db_insert('block_node_type')->fields(array('type', 'module', 'delta'));
  foreach (array('study', 'study_information','study_documents','contact','institution') as $type) {
    $query->values(array(
      'type' => $type,
      'module' => 'node_reference_block',
      'delta' => 'related-content',
    ));
  }
  $query->execute();
}